#!/usr/bin/env node

/**
 * Unified Dev Script for Worktree Testing
 *
 * Starts both mock-server and web-ui with automatic auth bypass.
 * Mock-server finds a free port automatically and communicates it to web-ui.
 * Automatically detects git branch and available Vite port.
 */

import { exec, execSync, spawn } from "child_process";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { existsSync, writeFileSync } from "fs";
import { createServer } from "net";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Paths
const rootDir = join(__dirname, "../..");
const mockServerDir = join(rootDir, "mock-server");
const mockServerMod = join(mockServerDir, "mod.ts");

// Check if mock-server exists
if (!existsSync(mockServerMod)) {
  console.error("❌ Error: mock-server/mod.ts not found at", mockServerMod);
  process.exit(1);
}

let mockServerProcess = null;
let webUiProcess = null;
let mockServerPort = null;
let vitePort = null;
let branchName = null;

// Open URL in default browser (cross-platform)
function openBrowser(url) {
  const platform = process.platform;
  let command;
  let args;

  if (platform === "win32") {
    command = "cmd";
    args = ["/c", "start", url];
  } else if (platform === "darwin") {
    command = "open";
    args = [url];
  } else {
    command = "xdg-open";
    args = [url];
  }

  spawn(command, args, { stdio: "ignore" }).on("error", (error) => {
    console.warn("⚠️  Could not open browser:", error.message);
  });
}

// Detect git branch name
function getBranchName() {
  try {
    const branch = execSync("git rev-parse --abbrev-ref HEAD", {
      cwd: rootDir,
      encoding: "utf8",
    }).trim();
    return branch;
  } catch (error) {
    console.warn("⚠️  Could not detect git branch:", error.message);
    return "unknown";
  }
}

// Check if port is available
function isPortAvailable(port) {
  return new Promise((resolve) => {
    const server = createServer();
    server.once("error", () => resolve(false));
    server.once("listening", () => {
      server.close();
      resolve(true);
    });
    server.listen(port);
  });
}

// Find available port starting from a given port
async function findAvailablePort(startPort = 5174) {
  for (let port = startPort; port < startPort + 100; port++) {
    if (await isPortAvailable(port)) {
      return port;
    }
  }
  throw new Error("Could not find available port");
}

// Write BASE_URL to .env.local for Playwright
function writeEnvLocal(vitePort) {
  const envLocalPath = join(__dirname, "..", ".env.local");
  const baseUrl = `http://localhost:${vitePort}`;

  try {
    // Write .env.local with BASE_URL
    const content = `# Auto-generated by dev-mock.js - Do not commit
# This file is specific to this worktree
BASE_URL=${baseUrl}
`;
    writeFileSync(envLocalPath, content, "utf8");
    console.log(`✅ Created .env.local with BASE_URL=${baseUrl}`);
  } catch (error) {
    console.warn("⚠️  Could not write .env.local:", error.message);
  }
}

// Cleanup function
function cleanup() {
  console.log("\n🛑 Shutting down services...");

  if (webUiProcess) {
    console.log("   Stopping web-ui...");
    webUiProcess.kill("SIGTERM");
  }

  if (mockServerProcess) {
    console.log("   Stopping mock-server...");
    mockServerProcess.kill("SIGTERM");
  }

  // Force kill after 3 seconds if processes don't exit gracefully
  setTimeout(() => {
    if (webUiProcess && !webUiProcess.killed) {
      webUiProcess.kill("SIGKILL");
    }
    if (mockServerProcess && !mockServerProcess.killed) {
      mockServerProcess.kill("SIGKILL");
    }
    process.exit(0);
  }, 3000);
}

// Handle process termination
process.on("SIGINT", cleanup);
process.on("SIGTERM", cleanup);
process.on("exit", cleanup);

// Wait for mock-server to be ready
async function waitForMockServer(port, maxAttempts = 30) {
  const healthUrl = `http://localhost:${port}/health`;

  for (let i = 0; i < maxAttempts; i++) {
    try {
      const response = await fetch(healthUrl);
      if (response.ok) {
        const data = await response.json();
        // Verify port matches
        if (data.port === port) {
          return true;
        }
      }
    } catch (error) {
      // Server not ready yet, continue waiting
    }

    // Wait 200ms before next attempt
    await new Promise((resolve) => setTimeout(resolve, 200));
  }

  return false;
}

// Parse port from mock-server stdout
function parsePortFromOutput(data) {
  const output = data.toString();
  const match = output.match(/MOCK_SERVER_PORT=(\d+)/);
  if (match) {
    const port = parseInt(match[1], 10);
    // Validate that the port is a valid number
    if (!isNaN(port) && port > 0 && port < 65536) {
      return port;
    }
  }
  return null;
}

// Start mock-server
function startMockServer() {
  return new Promise((resolve, reject) => {
    console.log("🚀 Starting mock-server...");

    mockServerProcess = spawn(
      "deno",
      ["run", "--allow-net", "--allow-env", "--watch", mockServerMod],
      {
        cwd: mockServerDir,
        stdio: ["ignore", "pipe", "pipe"],
        shell: true,
      },
    );

    let stdoutBuffer = "";
    let stderrBuffer = "";

    mockServerProcess.stdout.on("data", (data) => {
      stdoutBuffer += data.toString();
      // Add prefix to make mock-server logs visible
      const lines = data.toString().split("\n");
      lines.forEach((line) => {
        if (line.trim()) {
          console.log(`[mock-server] ${line}`);
        }
      });

      // Try to parse port from output
      const port = parsePortFromOutput(data);
      if (port && !mockServerPort) {
        mockServerPort = port;
        console.log(`\n✅ Mock-server port detected: ${port}`);
      }
    });

    mockServerProcess.stderr.on("data", (data) => {
      stderrBuffer += data.toString();
      // Add prefix to make mock-server errors visible
      const lines = data.toString().split("\n");
      lines.forEach((line) => {
        if (line.trim()) {
          console.error(`[mock-server] ${line}`);
        }
      });
    });

    mockServerProcess.on("error", (error) => {
      console.error("❌ Failed to start mock-server:", error.message);
      reject(error);
    });

    mockServerProcess.on("exit", (code) => {
      if (code !== 0 && code !== null) {
        console.error(`❌ Mock-server exited with code ${code}`);
        if (stderrBuffer) {
          console.error("Error output:", stderrBuffer);
        }
        reject(new Error(`Mock-server exited with code ${code}`));
      }
    });

    // Wait a bit for server to start, then check for port
    setTimeout(async () => {
      // If we haven't parsed the port yet, try to get it from health endpoint
      if (!mockServerPort) {
        // Try common ports
        for (let port = 8085; port < 8095; port++) {
          const ready = await waitForMockServer(port, 5);
          if (ready) {
            mockServerPort = port;
            console.log(
              `✅ Mock-server port detected via health check: ${port}`,
            );
            break;
          }
        }
      }

      if (mockServerPort) {
        // Verify server is ready
        const ready = await waitForMockServer(mockServerPort);
        if (ready) {
          resolve(mockServerPort);
        } else {
          reject(new Error("Mock-server did not become ready"));
        }
      } else {
        reject(new Error("Could not determine mock-server port"));
      }
    }, 1000);
  });
}

// Start web-ui
function startWebUi(mockPort, vitePort, branch) {
  return new Promise((resolve, reject) => {
    console.log(
      `🚀 Starting web-ui on port ${vitePort} with mock-server port ${mockPort}...`,
    );
    console.log(`   Branch: ${branch}`);

    // Set environment variables for Vite and Playwright
    const env = {
      ...process.env,
      VITE_MOCK_SERVER_PORT: mockPort.toString(),
      VITE_SKIP_AUTH: "true",
      VITE_BRANCH_NAME: branch,
      BASE_URL: `http://localhost:${vitePort}`,
    };

    webUiProcess = spawn(
      "npm",
      ["run", "dev", "--", "--port", vitePort.toString()],
      {
        cwd: join(__dirname, ".."),
        stdio: ["ignore", "pipe", "pipe"],
        env,
        shell: true,
      },
    );

    // Pipe web-ui output with prefix
    webUiProcess.stdout.on("data", (data) => {
      const lines = data.toString().split("\n");
      lines.forEach((line) => {
        if (line.trim()) {
          console.log(`[vite] ${line}`);
        }
      });
    });

    webUiProcess.stderr.on("data", (data) => {
      const lines = data.toString().split("\n");
      lines.forEach((line) => {
        if (line.trim()) {
          console.error(`[vite] ${line}`);
        }
      });
    });

    webUiProcess.on("error", (error) => {
      console.error("❌ Failed to start web-ui:", error.message);
      reject(error);
    });

    webUiProcess.on("exit", (code) => {
      if (code !== 0 && code !== null) {
        console.error(`❌ Web-ui exited with code ${code}`);
        reject(new Error(`Web-ui exited with code ${code}`));
      }
    });

    // Give it a moment to start
    setTimeout(() => {
      const webUiUrl = `http://localhost:${vitePort}`;
      console.log("\n✅ Both services are running!");
      console.log(`   Mock-server: ws://localhost:${mockPort}/ws`);
      console.log(`   Web-ui: ${webUiUrl}`);
      console.log(`   Branch: ${branch}`);
      console.log(`\n   💡 Playwright tests will use: BASE_URL=${webUiUrl}`);
      console.log("   Press Ctrl+C to stop both services\n");

      console.log(`🌐 Opening browser to ${webUiUrl}...`);
      openBrowser(webUiUrl);

      resolve();
    }, 2000);
  });
}

// Main execution
async function main() {
  try {
    // Detect branch name
    branchName = getBranchName();
    console.log(`📋 Detected branch: ${branchName}`);

    // Find available Vite port
    vitePort = await findAvailablePort(5174);
    console.log(`🔍 Found available Vite port: ${vitePort}`);

    // Write .env.local for Playwright
    writeEnvLocal(vitePort);

    // Start mock-server and get its port
    const mockPort = await startMockServer();
    mockServerPort = mockPort;

    // Start web-ui with detected ports and branch
    await startWebUi(mockPort, vitePort, branchName);
  } catch (error) {
    console.error("❌ Error:", error.message);
    cleanup();
    process.exit(1);
  }
}

main();
