export enum ErrorCode {
  // Claude Errors

  // Server Error
  OVERLOADED = "OVERLOADED",
  REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE",
  RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR",
  INVALID_REQUEST_ERROR = "INVALID_REQUEST_ERROR",
  CANCELLED = "CANCELLED",
  OTHER = "OTHER",
}
